-:
	cargo b --example color_change
	cargo b --example dialog
	cargo b --example frameless
	cargo b --example fullscreen
	cargo b --example graceful_exit
	cargo b --example minimal
	cargo b --example multi_window
	cargo b --example pageload
	cargo b --example simple_grep
	cargo b --example timer
	cargo b --example title_change
	cargo b --example todo
	cargo b --example pageload
