-:
	cargo b --example color_change || true
	cargo b --example dialog || true
	cargo b --example frameless || true
	cargo b --example fullscreen || true
	cargo b --example graceful_exit || true
	cargo b --example minimal || true
	cargo b --example multi_window || true
	cargo b --example pageload || true
	cargo b --example simple_grep || true
	cargo b --example timer || true
	cargo b --example title_change || true
	cargo b --example todo || true
	cargo b --example pageload || true
