on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    name: rustfmt
    steps:
      - uses: actions/checkout@v1

      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          #components: rustfmt
          override: true

      - name: install rustfmt
        run: rustup component add rustfmt

      - name: install clippy
        run: rustup component add clippy

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  test-stable:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macOS-latest, windows-2019, ubuntu-latest]
        os: [ubuntu-latest, macos-latest]
        examples: [actix, color_change, dialog, elm-counter, frameless, fullscreen, graceful_exit, minimal, multi_window, pageload, simple_grep, timer, title_change, todo, todo-elm, todo-purescript, todo-vue, todo-yew]

    name: cargo test stable
    steps:
      - uses: actions/checkout@v1

      - name: install libgtk-dev libwebkit2gtk-4.0
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.0-dev
        if: contains(matrix.os, 'ubuntu')

      - name: brew install gtk-mac-integration
        run: |
          brew install gtk-mac-integration
        if: contains(matrix.os, 'macos')

      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: make webview-examples
        run: make webview-examples
        if: contains(matrix.os, 'ubuntu')

      - name: cargo test --workspace --example matrix.examples
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --example ${{ matrix.examples }}
        if: contains(matrix.os, 'ubuntu')

      - name: cargo test --workspace --doc
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --doc
        if: contains(matrix.os, 'ubuntu')

  test-nightly:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macOS-latest, windows-2019, ubuntu-latest]
        os: [ubuntu-latest, macos-latest]
    name: cargo test nightly
    steps:
      - uses: actions/checkout@v1

      - name: install libgtk-dev libwebkit2gtk-4.0
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.0-dev
        if: contains(matrix.os, 'ubuntu')

      - name: brew install gtk-mac-integration
        run: |
          brew install gtk-mac-integration
        if: contains(matrix.os, 'macos')

      - name: install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
        #if: contains(matrix.os, 'ubuntu')

      - name: make webview-examples
        run: make webview-examples
        #if: contains(matrix.os, 'ubuntu')

      - name: cargo test --workspace --all-targets
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-targets
        if: contains(matrix.os, 'ubuntu')

      - name: cargo test --workspace --doc
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --doc
        if: contains(matrix.os, 'ubuntu')

  check-docs:
    name: Docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macOS-latest, windows-2019, ubuntu-latest]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1

      - name: install libgtk-dev libwebkit2gtk-4.0
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.0-dev
        if: contains(matrix.os, 'ubuntu')

      - name: install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
        #if: contains(matrix.os, 'ubuntu')

      - name: check docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --document-private-items
        if: contains(matrix.os, 'ubuntu')
